routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify'=>true]);


Route::group(['as'=>'admin.', 'prefix' => 'admin','namespace'=>'admin','middleware'=>['auth','admin','verified']], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::post('/dashboard/', 'DashboardController@store')->name('store');
    Route::get('/dashboard/js', 'DashboardController@jsonCreate')->name('jsonCreate');
    Route::put('/dashboard/{candidate}', 'DashboardController@update')->name('update');
    Route::delete('/dashboard/{candidate}', 'DashboardController@destroy')->name('delete');
    
});
Route::group(['as'=>'voter.', 'prefix' => 'voter','namespace'=>'voter','middleware'=>['auth','voter','verified']], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::post('/dashboard', 'DashboardController@store')->name('store');
    Route::put('/dashboard/{user}/{candidate}', 'DashboardController@update')->name('update');
    Route::delete('/dashboard/{candidate}', 'DashboardController@destroy')->name('delete');
     
});
Route::get('/dashboard/results','HomeController@index')->name('resultados')->middleware('auth');

resources/views/Admin/dashboard.blade.php
@extends('layouts.app')

@push('css')
   <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endpush
@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul class="list-group">
                @foreach ($errors->all() as $erro)
                    <li class="list-group-item text-danger">
                        {{$erro}}
                    </li>
                @endforeach
            </ul>
        </div>
    @endif

 <div class="card shadow mb-4 ">
            <div class="card-header py-3 bg-gradient-primary ">
              <a href="#" class=" btn btn-sm btn-primary shadow-sm"   data-toggle="modal" data-target="#createCategory"><i class="fas fa-plus fa-sm text-white-50"></i>Create Candidate</a>
               <a href="{{ route('resultados') }}" class="btn btn-success btn-circle btn-sm shadow-sm mr-4"><i class="fas fa-eye"></i>   Visualizar resultados</a>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Nome do candidato</th>
                      <th>Votos</th>
                      <th>Editar</th>
                      <th>Deletar</th>
                    </tr>
                  </thead>
                  <tbody>
                        @foreach ($candidates as $candidate)
                            <tr>
                                <td>{{$candidate->name}}</td>
                                <td>{{$candidate->users->count()}}</td>
                                <td>
                                    <a href="#" class="btn btn-warning btn-circle btn-sm shadow-sm" onclick="update_cat({{$candidate->id}},'{{$candidate->name}}')"><i class="fas fa-edit"></i></a>
                                </td>
                                <td> 
                                    <a href="#" class="btn btn-danger btn-circle btn-sm shadow-sm" onclick="delete_cat({{$candidate->id}})"><i class="fas fa-trash"></i></a>
                                </td>
                            </tr>
                        @endforeach           
                  </tbody>
                </table>
              </div>
            </div>
          </div>

          {{--Modal of create and update category--}}


  <div class="modal fade" id="createCategory" tabindex="-1" role="dialog" aria-labelledby="category" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header bg-gradient-primary">
            <span class="font-weight-bold" id="category">New candidate</span>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">
            
            <form id="category_create" action="{{ route('admin.store') }}" method="POST">
                @csrf
                @method('POST')
                <div class="row">
                    <div class="col-sm-12">
                        <input type="text" name="name" class="form-control" placeholder="create candidate">
                    </div>
                </div>
            </form>

        </div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{{ route('admin.store') }}" onclick="event.preventDefault();document.getElementById('category_create').submit();">Create</a>
          
        </div>
      </div>
    </div>
  </div>
{{-- update category modal--}}

  <div class="modal fade" id="UpdateCategory" tabindex="-1" role="dialog" aria-labelledby="category" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header bg-gradient-warning">
          <span class="font-weight-bold" id="category_up">Update candidate</span>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">
            
            <form name="Update_Category" id="category_update" method="POST">
                @csrf
                @method('PUT')
                <div class="row">
                    <div class="col-sm-12">
                        <input id="category_update_name" type="text" name="name" class="form-control" placeholder="update candidate">
                    </div>
                </div>
            </form>

        </div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary"  onclick="event.preventDefault();document.getElementById('category_update').submit();">Update</a>
        </div>
      </div>
    </div>
  </div>

{{--Modal of Delete category--}}




<div id="addNewAddonCategoryModal" class="modal fade" tabindex="-1">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header bg-gradient-danger">
                <h6 class="modal-title "><span class="font-weight-bold">Delete category</span></h6>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <div class="alert alert-warning container">Are you sure ?</div>
                <form action="" method="POST" id="deleteCat">
                    @method('DELETE')
                    @csrf

               
                <button type="submit" class=" btn btn-primary btn-sm" data-dismiss="modal">
                        No . go back
                </button>
                <input type="submit" class="btn btn-danger btn-sm" value="yes . delete">
                        
                 </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    function delete_cat(id){
        var form = document.getElementById('deleteCat');
        form.action = 'dashboard/'+id;
        console.log(form);
        $('#addNewAddonCategoryModal').modal('show');
    };

    function update_cat(id,name) {
        var form  = document.getElementById('category_update');
        form.action = 'dashboard/'+id;
        document.forms["Update_Category"]["name"].value = name;
        console.log(form);
        $('#UpdateCategory').modal('show');
    };


  




</script>

@endsection

@push('js')
<script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
  <!-- Page level custom scripts -->
  <script src="{{ asset('js/demo/datatables-demo.js') }}"></script>
@endpush