routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify'=>true]);


Route::group(['as'=>'admin.', 'prefix' => 'admin','namespace'=>'admin','middleware'=>['auth','admin','verified']], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::post('/dashboard/', 'DashboardController@store')->name('store');
    Route::get('/dashboard/js', 'DashboardController@jsonCreate')->name('jsonCreate');
    Route::put('/dashboard/{candidate}', 'DashboardController@update')->name('update');
    Route::delete('/dashboard/{candidate}', 'DashboardController@destroy')->name('delete');
    
});
Route::group(['as'=>'voter.', 'prefix' => 'voter','namespace'=>'voter','middleware'=>['auth','voter','verified']], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::post('/dashboard', 'DashboardController@store')->name('store');
    Route::put('/dashboard/{user}/{candidate}', 'DashboardController@update')->name('update');
    Route::delete('/dashboard/{candidate}', 'DashboardController@destroy')->name('delete');
     
});
Route::get('/dashboard/results','HomeController@index')->name('resultados')->middleware('auth');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
   

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
      <link href="{{asset('vendor/fontawesome-free/css/all.min.css')}}" rel="stylesheet" type="text/css">

  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    
  @stack('css')
  <style>
      .main-header{
          position:-webkit-sticky; 
          position:sticky; 
          top:0;
          z-index: 9000;
          }
      </style>
</head>
<body >
    
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm main-header">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>


                 <a class="navbar-brand" href="{{ route('admin.dashboard') }}">
                    {{ __('Painel do Eleitor') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4 col-sm-12">
             @if (session()->has('success'))
                            <div id="alert-session" class=" shadow-sm alert alert-success alert-session alert-dismissible fadeInDown animated  show container col-sm-8 --green">
                                {{session()->get('success')}}
                            </div>
                        @endif
                        @if (session()->has('error'))
                            <div id="alert-danger" class="shadow-sm alert alert-danger alert-dismissible fadeInDown animated  show container col-sm-8 --green">
                                {{session()->get('error')}}
                            </div>
                        @endif
            @yield('content')
        </main>
    </div>
</body>
  <script src="{{ asset('vendor/jquery/jquery.min.js') }}"></script>
  <script src="{{ asset('vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{{ asset('vendor/jquery-easing/jquery.easing.min.js') }}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{{ asset('js/sb-admin-2.min.js') }}"></script>

  @stack('js')
  <script type="text/javascript">
      $(document).ready(function() {
    // show the alert
    setTimeout(function() {
        $("#alert-session").addClass('fadeOutUp');
    }, 2000);
    setTimeout(function() {
        $("#alert-session").alert('close');
    }, 3000);

    setTimeout(function() {
        $("#alert-session-js").addClass('fadeOutUp');
    }, 2000);
    setTimeout(function() {
        $("#alert-session-js").alert('close');
    }, 3000);
    
});
  </script>

  <script type="text/javascript">
      $(document).ready(function() {
    // show the alert
    setTimeout(function() {
        $("#alert-danger").addClass('fadeOutUp');
    }, 2000);
    setTimeout(function() {
        $("#alert-danger").alert('close');
    }, 3000);

    $(document).on('mousemove',function(){
         setTimeout(function() {
        $("#alert-session-js-js").addClass('fadeOutUp');
    }, 2000);
    setTimeout(function() {
        $("#alert-session-js-js").alert('close');
    }, 3000);
    
    });

    
});
  </script>
</html>